### ISSUE TITLE
ДЗ2

### ISSUE THREAD

**Issue by anrom7** [Vozak16/Gmail-Manager#2]
Не знайшов

**Comment by Vozak16** [comment]
Доброї ночі, пане Андрію. Ми щось занадто захопилися самою реалізацією нашого проекту, і почали писати вже сам код без належного планування і слідування по серіям дз. Вже зараз зрозуміли, що краще робити все поступово та мати належний опис всіх своїх дій, планів та коду, тоді комунікація між членами команди значно легша і зрозуміліша. Поки у нас написаний код випереджає домашні завдання. Виправляємся!) Домашнє завдання №2 вже готове, дз3 і дз4 ще в процесі.
